baseURL = "https://docs.emrys.io"
title = "emrys"

theme = "book"

# (Optional) Set this to true if you use captial letters in file names
disablePathToLower = true

[params]
  AuthorName = "William Minshew"
  GitHubUser = "wminshew"
  EmrysURL = "https://www.emrys.io"
  EmrysSupport = "support@emrys.io"
  EmrysTwitter = "emrysio"
  EmrysVersion = "u0.6.0_m0.6.0"

  # (Optional, default true) Show or hide table of contents globally
  # You can also specify this parameter per page in front matter
  # BookShowToC = true

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  BookMenuBundle = "menu"

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  # BookSection = "docs"
